### ISSUE TITLE
armv7环境本地运行失败

### ISSUE THREAD

**Issue by walkonbothsides** [yinxin630/fiora#136]
```
root@orangepione:pi/fiora ‹master›# npm run server

> fiora@0.0.1 server /home/pi/fiora
> cross-env NODE_ENV=development && nodemon server/main.ts --exec './node_modules/.bin/ts-node' --config .nodemonrc

[nodemon] 1.19.1
[nodemon] reading config ./.nodemonrc
[nodemon] to restart at any time, enter `rs`
[nodemon] or send SIGHUP to 4123 to restart
[nodemon] ignoring: client/**/* build/**/* test/**/* public/**/* dist/**/* test.js
[nodemon] watching: *.*
[nodemon] watching extensions: ts,json
[nodemon] starting `./node_modules/.bin/ts-node server/main.ts`
[nodemon] spawning
[nodemon] child pid: 4137
[nodemon] watching 248 files
Error: Cannot find module 'koa-send'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/home/pi/fiora/server/app.ts:3:1)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Module.m._compile (/home/pi/fiora/node_modules/ts-node/src/index.ts:473:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/home/pi/fiora/node_modules/ts-node/src/index.ts:476:12)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/home/pi/fiora/server/main.ts:3:1)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
[nodemon] app crashed - waiting for file changes before starting...


```
QAQ

**Comment by yinxin630** [comment]
缺少依赖包, 执行 `yarn` 重装依赖
