### ISSUE TITLE
fiora command

### ISSUE THREAD

**Issue by abyong123** [yinxin630/fiora#480]
hi how can i execute fiora command and where?

**Comment by yinxin630** [comment]
You should cd into fiora root directory. And then execute `fiora [command]`.

If fiora is not a valid command. You can execute `npm link` or `yarn link` to install it

**Comment by abyong123** [comment]
now its showing me this. . . 



root@fiora:~/fiora# fiora deleteMessages
/root/fiora/node_modules/ts-node/src/index.ts:820
    return new TSError(diagnosticText, diagnosticCodes);
           ^
{ TSError: ⨯ Unable to compile TypeScript:
packages/i18n/node.index.ts:1:22 - error TS2307: Cannot find module 'os-locale' or its corresponding type declarations.

1 import osLocale from 'os-locale';
                       ~~~~~~~~~~~

    at createTSError (/root/fiora/node_modules/ts-node/src/index.ts:820:12)
    at reportTSError (/root/fiora/node_modules/ts-node/src/index.ts:824:19)
    at getOutput (/root/fiora/node_modules/ts-node/src/index.ts:1014:36)
    at Object.compile (/root/fiora/node_modules/ts-node/src/index.ts:1322:43)
    at Module.m._compile (/root/fiora/node_modules/ts-node/src/index.ts:1454:30)
    at Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/root/fiora/node_modules/ts-node/src/index.ts:1458:12)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3) diagnosticCodes: [ 2307 ] }
