### ISSUE TITLE
fiora 内置命令行报错。

### ISSUE THREAD

**Issue by Yeluoxc** [yinxin630/fiora#503]
系统为ubuntu18.04，只有几个命令能用，fiora、fiora doctor命令也是这样。

`root@instance-20220701-2238:~/fiora#` fiora getUserId 用户名

/root/fiora/packages/i18n/node.index.ts:15
    return languages[locale][key] || enUS[key] || key;
                            ^
TypeError: Cannot read property 'getUserIdDescription' of undefined
    at Object.i18n [as default] (/root/fiora/packages/i18n/node.index.ts:15:29)
    at Object.<anonymous> (/root/fiora/index.ts:14:22)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Module.m._compile (/root/fiora/node_modules/ts-node/src/index.ts:1225:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Object.require.extensions.<computed> [as .ts] (/root/fiora/node_modules/ts-node/src/index.ts:1228:12)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at main `(/root/fiora/node_modules/ts-node/src/bin.ts:330:12)`

**Comment by Yeluoxc** [comment]
arm64的

**Comment by 1749401557** [comment]
我怎么直接不能用这个命令

**Comment by cancundeyingzi** [comment]
我连fiora 都not found

**Comment by qtlark** [comment]
修改/root/fiora/packages/i18n/node.index.ts文件

将函数改为：


```
export default function i18n(key: keyof typeof enUS | keyof typeof zhCN) {
    // @ts-ignore
    return enUS[key] || key;
}
```


即可
