### ISSUE TITLE
400 Bad Request Request Header Or Cookie Too Large

### ISSUE THREAD

**Issue by biliyoyo520** [yinxin630/fiora#510]
照着教程搭好了端口开好了
访问的时候出现400错误
改了nginx配置也没用怎么办qwq

**Comment by biliyoyo520** [comment]
root@SECS9l34d:/opt/fiora# yarn start
yarn run v1.22.19
$ npx lerna run start --stream
lerna notice cli v4.0.0
lerna info versioning independent
lerna info Executing command in 1 package: "yarn run start"
@fiora/server: $ cross-env NODE_ENV=production DOTENV_CONFIG_PATH=../../.env ts-node -r dotenv/config --transpile-only src/main.ts
@fiora/server: Error: listen EADDRINUSE: address already in use :::9200
@fiora/server:     at Server.setupListenHandle [as _listen2] (node:net:1372:16)
@fiora/server:     at listenInCluster (node:net:1420:12)
@fiora/server:     at Server.listen (node:net:1508:7)
@fiora/server:     at /opt/fiora/packages/server/src/main.ts:32:9
@fiora/server:     at Generator.next (<anonymous>)
@fiora/server:     at fulfilled (/opt/fiora/packages/server/src/main.ts:5:58)
@fiora/server:     at processTicksAndRejections (node:internal/process/task_queues:96:5)
@fiora/server: error Command failed with exit code 1.
@fiora/server: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
lerna ERR! yarn run start exited 1 in '@fiora/server'
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
root@SECS9l34d:/opt/fiora# netstat -ap | grep 9200
tcp        0      0 0.0.0.0:9200            0.0.0.0:*               LISTEN      314125/nginx: worke 
root@SECS9l34d:/opt/fiora# kill -9 314125
root@SECS9l34d:/opt/fiora# yarn start
yarn run v1.22.19
$ npx lerna run start --stream
lerna notice cli v4.0.0
lerna info versioning independent
lerna info Executing command in 1 package: "yarn run start"
@fiora/server: $ cross-env NODE_ENV=production DOTENV_CONFIG_PATH=../../.env ts-node -r dotenv/config --transpile-only src/main.ts
@fiora/server: Error: listen EADDRINUSE: address already in use :::9200
@fiora/server:     at Server.setupListenHandle [as _listen2] (node:net:1372:16)
@fiora/server:     at listenInCluster (node:net:1420:12)
@fiora/server:     at Server.listen (node:net:1508:7)
@fiora/server:     at /opt/fiora/packages/server/src/main.ts:32:9
@fiora/server:     at Generator.next (<anonymous>)
@fiora/server:     at fulfilled (/opt/fiora/packages/server/src/main.ts:5:58)
@fiora/server:     at processTicksAndRejections (node:internal/process/task_queues:96:5)
@fiora/server: error Command failed with exit code 1.
@fiora/server: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
lerna ERR! yarn run start exited 1 in '@fiora/server'
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
